name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: set-matrix
      run: |
        cat output.json
        echo "::set-output name=matrix::{\"include\":$( cat output.json)}"
  job2:
    needs: job1
    if: ${{ needs.job1.outputs.matrix }}!="{\"include\":[]}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    env:
      PODSPEC: ${{ matrix.podsepc }}
      MATRIX: ${{ needs.job1.outputs.matrix }}
    steps:
    - run: echo ${{ needs.job1.outputs.matrix }}
