name: tag_generation

on: [pull_request]

jobs:
  test_tmp_tag:
  runs-on: 	macos-11
  env:
    test_token: ${{ secrets.TEST_TOKEN }}
  steps:
    - name: Get PR number
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo $pull_number

